title: Ashok A R
logo: https://github.com/ashokrajagopal68/Projects/blob/d307c9ae0adf5145cbdd85d2d8c36919ec0e9dc9/assets/img/IMG_20200614_114921%20(1).jpg
description: Aspiring Data Scientist
show_downloads: False
google_analytics:
theme: jekyll-theme-minimal
